version: '3.7'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - docker/env
    entrypoint: /code/entrypoint.backend.dev.sh

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.frontend
    command: /bin/sh -c "yarn install && yarn serve"
    volumes:
      - ./frontend/:/code
      - /code/node_modules
    ports:
      - 8080:8080
    depends_on:
      - backend

  rabbit:
    image: "rabbitmq:3.7.14-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    build:
      context: backend/
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/:/code
    command: celery -A stepik worker -l INFO
    restart: always
    depends_on:
      - rabbit
      - backend
    entrypoint: /code/entrypoint.backend.dev.sh