FROM python:3.9-slim-buster
ENV PYTHONBUFFERED 1

RUN apt update

RUN apt install -y netcat
RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/
COPY ./entrypoint.backend.dev.sh /code/
