# Generated by Django 2.2 on 2021-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('evaluation', 'Оценивается'), ('correct', 'Верно'), ('wrong', 'Неверно'), ('unevaluated', 'Серверная ошибка при оценивании')], default='evaluation', max_length=32)),
                ('code', models.TextField()),
                ('checker_identifier', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
