# Generated by Django 2.2 on 2021-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('start_dt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('evaluation', 'Оценивается'), ('correct', 'Верно'), ('wrong', 'Неверно')], max_length=32)),
            ],
        ),
    ]
